# Generated by Django 6.1.1 on 2026-09-07 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(default='Headquarters Dispatch', max_length=150)),
                ('name', models.CharField(max_length=200, verbose_name='Full / Farm Name')),
                ('phone', models.CharField(max_length=30)),
                ('product', models.CharField(choices=[('Day Old Chicks', 'Day Old Chicks (Broiler / Layer)'), ('Premix & Feed', 'Premix & Feed Additives'), ('Vaccines', 'Vaccines & Medications'), ('Equipment', 'Farm Equipment')], default='Day Old Chicks', max_length=100)),
                ('quantity', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Request',
                'verbose_name_plural': 'Booking Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
