# Generated by Django 6.1.1 on 2026-09-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
