# Generated by Django 6.1.1 on 2026-09-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('salary', models.CharField(help_text='e.g., ₦500,000/month or Competitive', max_length=100)),
                ('description', models.TextField(help_text='Full job responsibilities and requirements')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this job from the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
